### ISSUE TITLE
Validation messages not loaded from translations

### ISSUE THREAD

**Issue by thibaultlavoisey** [spatie/laravel-validation-rules#26]
Hi! 👋 

First, thank you for this package :) It works great, but it seems that validation messages aren't loaded from translations: 

<img width="351" alt="Screenshot 2019-06-02 at 20 57 17" src="https://user-images.githubusercontent.com/2022117/58765956-1288c100-8579-11e9-98d2-8f29750920c4.png">

I fixed the issue by changing the `Enum` rule code as follow:

<img width="577" alt="Screenshot 2019-06-02 at 20 58 46" src="https://user-images.githubusercontent.com/2022117/58765977-61cef180-8579-11e9-9114-2401032debfc.png">

<img width="350" alt="Screenshot 2019-06-02 at 20 59 41" src="https://user-images.githubusercontent.com/2022117/58765978-672c3c00-8579-11e9-834f-8ec477b305a4.png">

Am I doing something wrong?

Thanks for your help!

**Comment by atymic** [comment]
Hmm, strange.
I can reproduce the behaviour on a fresh 5.8 install :thinking: 	
```
MessageBag {#323 ▼
  #messages: array:1 [▼
    "test" => array:1 [▼
      0 => "validation.country_code"
    ]
  ]
  #format: ":message"
}
```

I'll submit a PR to fix the problem.

**Comment by atymic** [comment]
PR Open #27 :smile:

**Comment by freekmurze** [comment]
We'll continue this in #27
