### ISSUE TITLE
Delimited validation

### ISSUE THREAD

**Issue by e-nikitin** [spatie/laravel-validation-rules#29]
'filter.price_between' => (new Delimited('numeric'))->min(2)->max(2)->allowDuplicates()
Input:
      0,539000000
result:
 "message": "The given data was invalid.",
    "errors": {
        "filter.price_between": [
            "validation.delimited.min"
        ]
    }
when put 0 as value into min(2) validate functions, we get error, and result is the same, as we didn't put any value

**Comment by freekmurze** [comment]
Could you PR a failing test for me to look at?

**Comment by e-nikitin** [comment]
This code 

```
$validator = Validator::make([
            'f' => '0,9999'
        ], [
            'f' => (new Delimited('numeric'))->min(2)->max(2),
        ]);

dd($validator->errors()->messages());
```

gives  such result:

```
array:1 [
  "f" => array:1 [
    0 => "validation.delimited.min"
  ]
]
```
I give two values (0 and 9999) but it seems as I give only one value 9999
