### ISSUE TITLE
Delimited rule ignored when using date_format

### ISSUE THREAD

**Issue by Scumi** [spatie/laravel-validation-rules#49]
On Laravel 8.61, the Delimited rule appears to be ignored when using date_format validation.
When I separate via space, colon, semi-colon (instead of the intended comma), the FormRequest always prompts the date_format-rule failing (event though the actual date format is fine). 

```
    public function rules()
    {
        return [
            'date' => [
                new Delimited('date_format:"d.m.Y"')
            ]
        ];
    }
```

**Comment by freekmurze** [comment]
You you PR a test for this that proves that this is failing (and possible also PR a fix)?

**Comment by Scumi** [comment]
That was a good idea. I realized that I misinterpreted the behaviour of the rule. I though if non-specified separators are used, the Delimited-rule would provide an error message that informs me about this, rather than failing the provided "sub"-rule.
