### ISSUE TITLE
Delimiter doNotTrimItems throwing error

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-validation-rules#55]
Laravel: v9.22.1
PHP: v8.1.7
Package: v3.2.0

I get
```
Method Illuminate\Validation\Validator::validate1 does not exist.
```

When using either of these
```
return [
    'emails' => [(new Delimited('email'))->doNotTrimItems()],
];
```
```
return [
    'emails' => [(new Delimited('email'))->max(5)->doNotTrimItems()],
];
```

Then I get
```
Call to a member function max() on bool
```

When using
```
return [
    'emails' => [(new Delimited('email'))->doNotTrimItems()->max(5)],
];
```

**Comment by freekmurze** [comment]
It seems like the surrounding tests are passing: https://github.com/spatie/laravel-validation-rules/blob/main/tests/Rules/DelimitedTest.php

Could you PR a failing test for us to look at?

**Comment by bbashy** [comment]
I fixed it locally by changing https://github.com/spatie/laravel-validation-rules/blob/main/src/Rules/Delimited.php#L72 to `return $this;`

I will try submit a test for it failing now.
